---
version: '3.8'
services:
  ca:
    build: ./root-ca
    container_name: ca
    volumes:
      - ./root-ca/ca_data/:/etc/ssl/ca
    command: generate_ca.sh
 
  signer:
    build: ./signer
    container_name: signer
    depends_on:
      - ca
    volumes:
      - ./signer/signer_data:/etc/ssl/signer
      - ./root-ca/ca_data:/etc/ssl/ca:ro
    environment:
      - FQDN=${FQDN}
    command: generate_cert.sh

volumes:
  ca_data:
  signer_data:
